language: python
sudo: false
python:
  - 2.7
  - 3.6
env:
  - DJANGO="Django==1.11.14"
  - DJANGO="Django==2.0.7"
  - DJANGO="https://www.djangoproject.com/download/2.1rc1/tarball/"
install:
  - pip install $DJANGO
  - pip install -r testproject/requirements.txt
  - pip install -r testproject/requirements_test.txt
  - pip install -r testproject/requirements_travis.txt
  - pip install -e .
script:
  - python testproject/manage.py test django_file_form_example
  - coverage run --source=django_file_form,testproject/django_file_form_example testproject/manage.py test django_file_form_example
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
  - python: 2.7
    env: DJANGO="Django==2.0.7"
  - python: 2.7
    env: DJANGO="https://www.djangoproject.com/download/2.1rc1/tarball/"
