language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: DJANGO="Django==1.11.16"
    - python: 3.6
      env: DJANGO="Django==1.11.16"
    - python: 3.7
      env: DJANGO="Django==2.0.9"
      dist: xenial
      sudo: true
    - python: 3.7
      env: DJANGO="Django==2.1.3"
      dist: xenial
      sudo: true
install:
  - pip install $DJANGO
  - pip install -r testproject/requirements.txt
  - pip install -r testproject/requirements_test.txt
  - pip install -r testproject/requirements_travis.txt
  - pip install -e .
script:
  - python testproject/manage.py test django_file_form_example
  - coverage run --source=django_file_form,testproject/django_file_form_example testproject/manage.py test django_file_form_example
  - coverage report
after_success:
  - coveralls
