language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - DJANGO="Django==1.8.19"
  - DJANGO="Django==1.9.13"
  - DJANGO="Django==1.10.8"
  - DJANGO="Django==1.11.12"
  - DJANGO="Django==2.0.4"
install:
  - pip install $DJANGO
  - pip install -r testproject/requirements.txt
  - pip install -r testproject/requirements_test.txt
  - pip install -r testproject/requirements_travis.txt
  - pip install -e .
script:
  - python testproject/manage.py test django_file_form_example
  - coverage run --source=django_file_form,testproject/django_file_form_example testproject/manage.py test django_file_form_example
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
  - python: 2.7
    env: DJANGO="Django==2.0.4"
